# Cocogitto configuration
# https://docs.cocogitto.io/config/

ignore_merge_commits = true
tag_prefix = "v"

# Update the workspace version in Cargo.toml before committing the release.
pre_bump_hooks = [
  "cargo set-version {{version}}",
  "cargo check --workspace",
  "git add Cargo.toml Cargo.lock",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "cargo-rigtest"
owner = "anthonyoteri"
authors = [
  { username = "anthonyoteri", signature = "Anthony Oteri" },
]

[commit_types]
feat     = { changelog_title = "Features" }
fix      = { changelog_title = "Bug Fixes" }
perf     = { changelog_title = "Performance" }
refactor = { changelog_title = "Refactoring" }
docs     = { changelog_title = "Documentation" }
test     = { changelog_title = "Tests" }
ci       = { changelog_title = "CI", omit_from_changelog = true }
chore    = { changelog_title = "Miscellaneous", omit_from_changelog = true }
