use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

/// A pinned, heap-allocated [`Future`] that is [`Send`] and bounded by lifetime `'a`.
///
/// This is the return type stored in [`TestCase::test_fn`],
/// [`GlobalSetupEntry::setup_fn`], and [`GlobalTeardownEntry::teardown_fn`].
/// You will not normally need to use it directly — the `#[testcase]`,
/// `#[global_setup]`, and `#[global_teardown]` proc macros generate the correct
/// wrappers automatically.
pub type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// Boxed error type returned from test functions, setup closures, and teardown
/// closures. Equivalent to `Box<dyn std::error::Error + Send + Sync>`.
pub type BoxError = Box<dyn std::error::Error + Send + Sync>;

/// The concrete type of the function pointer stored in [`TestCase::test_fn`].
///
/// It accepts a shared [`TestContext`][crate::context::TestContext] and returns
/// a [`BoxFuture`] that resolves to `Ok(())` on success or an error on failure.
/// You will not normally construct values of this type directly.
pub type TestFn = fn(Arc<crate::context::TestContext>) -> BoxFuture<'static, Result<(), BoxError>>;

/// A single test case registered at compile time via `#[testcase]`.
///
/// The `#[testcase]` attribute macro fills all fields automatically from the
/// annotated function and its attribute arguments.
///
/// Fields may be added in future releases. The `#[non_exhaustive]` attribute
/// prevents external code from constructing this struct via struct literal
/// syntax — use the `#[testcase]` macro.
#[non_exhaustive]
pub struct TestCase {
    /// The test name as it appears in output and filter expressions.
    ///
    /// Set to the Rust function name (e.g. `"my_test"`) by the `#[testcase]` macro.
    pub name: &'static str,
    /// The Rust module path where the test function was declared.
    ///
    /// Set by `module_path!()` inside the macro expansion — for example
    /// `"my_crate::integration"`.
    pub module: &'static str,
    /// The source file path where the test function was declared.
    ///
    /// Set by `file!()` inside the macro expansion — for example
    /// `"tests/integration.rs"`.
    pub file: &'static str,
    /// When `true` this test must not run concurrently with any other test.
    ///
    /// Set by `#[testcase(serial)]`.
    pub serial: bool,
    /// Kill the subprocess and record a failure if the test exceeds this duration.
    ///
    /// `None` means no timeout. Set by `#[testcase(timeout = Duration::from_secs(N))]`.
    pub timeout: Option<std::time::Duration>,
    /// Retry a failed test up to this many additional times before reporting failure.
    ///
    /// `0` means no retries (the test runs exactly once). Set by
    /// `#[testcase(retries = N)]`.
    pub retries: u32,
    /// Tags attached to this test, used by the `--tag` and `--not-tag` filters.
    ///
    /// Empty by default. Set by `#[testcase(tags = ["smoke", "regression"])]`.
    /// Tags are matched case-sensitively against the values supplied on the
    /// command line.
    pub tags: &'static [&'static str],
    /// The test function, receiving a shared [`TestContext`][crate::context::TestContext].
    ///
    /// Generated by the `#[testcase]` macro as a thin wrapper that boxes the
    /// user's `async fn` into a [`BoxFuture`].
    pub test_fn: TestFn,
}

impl TestCase {
    /// Constructs a [`TestCase`]. Intended for use by the `#[testcase]`
    /// proc macro; not part of the stable public API.
    #[doc(hidden)]
    #[must_use]
    #[allow(clippy::too_many_arguments)]
    pub const fn new(
        name: &'static str,
        module: &'static str,
        file: &'static str,
        serial: bool,
        timeout: Option<std::time::Duration>,
        retries: u32,
        tags: &'static [&'static str],
        test_fn: TestFn,
    ) -> Self {
        Self {
            name,
            module,
            file,
            serial,
            timeout,
            retries,
            tags,
            test_fn,
        }
    }
}

// linkme requires Sync
unsafe impl Sync for TestCase {}

/// A global setup function registered at compile time via `#[global_setup]`.
///
/// At most one entry may exist per test binary. The runtime calls [`setup_fn`]
/// once before running any tests, then uses [`serialize_fn`] to hand the state
/// to each test subprocess via an environment variable and [`deserialize_fn`]
/// to reconstruct it inside each subprocess.
///
/// Fields may be added in future releases. The `#[non_exhaustive]` attribute
/// prevents external code from constructing this struct via struct literal
/// syntax — use the `#[global_setup]` macro.
///
/// [`setup_fn`]: GlobalSetupEntry::setup_fn
/// [`serialize_fn`]: GlobalSetupEntry::serialize_fn
/// [`deserialize_fn`]: GlobalSetupEntry::deserialize_fn
#[non_exhaustive]
pub struct GlobalSetupEntry {
    /// Invokes the user's `#[global_setup]` function and returns its value as a
    /// type-erased `Box<dyn Any + Send + Sync>`.
    pub setup_fn: fn() -> BoxFuture<'static, Box<dyn std::any::Any + Send + Sync>>,
    /// Serializes the state value to a JSON string for subprocess handoff.
    ///
    /// The concrete type must implement `serde::Serialize`.
    pub serialize_fn: fn(&(dyn std::any::Any + Send + Sync)) -> String,
    /// Deserializes state from the JSON string produced by [`GlobalSetupEntry::serialize_fn`].
    ///
    /// The concrete type must implement `serde::de::DeserializeOwned`.
    pub deserialize_fn: fn(&str) -> Box<dyn std::any::Any + Send + Sync>,
}

impl GlobalSetupEntry {
    /// Constructs a [`GlobalSetupEntry`]. Intended for use by the
    /// `#[global_setup]` proc macro; not part of the stable public API.
    #[doc(hidden)]
    #[must_use]
    pub const fn new(
        setup_fn: fn() -> BoxFuture<'static, Box<dyn std::any::Any + Send + Sync>>,
        serialize_fn: fn(&(dyn std::any::Any + Send + Sync)) -> String,
        deserialize_fn: fn(&str) -> Box<dyn std::any::Any + Send + Sync>,
    ) -> Self {
        Self {
            setup_fn,
            serialize_fn,
            deserialize_fn,
        }
    }
}

unsafe impl Sync for GlobalSetupEntry {}

/// A global teardown function registered at compile time via `#[global_teardown]`.
///
/// At most one entry may exist per test binary. The runtime calls [`teardown_fn`]
/// once after all tests have run, passing the state produced by `#[global_setup]`.
///
/// Fields may be added in future releases. The `#[non_exhaustive]` attribute
/// prevents external code from constructing this struct via struct literal
/// syntax — use the `#[global_teardown]` macro.
///
/// [`teardown_fn`]: GlobalTeardownEntry::teardown_fn
#[non_exhaustive]
pub struct GlobalTeardownEntry {
    /// Invokes the user's `#[global_teardown]` function with the type-erased global
    /// state, consuming it.
    pub teardown_fn: fn(Box<dyn std::any::Any + Send + Sync>) -> BoxFuture<'static, ()>,
}

impl GlobalTeardownEntry {
    /// Constructs a [`GlobalTeardownEntry`]. Intended for use by the
    /// `#[global_teardown]` proc macro; not part of the stable public API.
    #[doc(hidden)]
    #[must_use]
    pub const fn new(
        teardown_fn: fn(Box<dyn std::any::Any + Send + Sync>) -> BoxFuture<'static, ()>,
    ) -> Self {
        Self { teardown_fn }
    }
}

unsafe impl Sync for GlobalTeardownEntry {}

/// A preflight builder function registered at compile time via `#[preflight]`.
///
/// At most one entry may exist per test binary. The coordinator calls
/// [`build_fn`] once at startup — before any `#[global_setup]` runs — to
/// obtain the declared [`Preflight`][crate::preflight::Preflight] and runs
/// every probe in parallel.
///
/// Fields may be added in future releases. The `#[non_exhaustive]` attribute
/// prevents external code from constructing this struct via struct literal
/// syntax — use the `#[preflight]` macro.
///
/// [`build_fn`]: PreflightEntry::build_fn
#[non_exhaustive]
pub struct PreflightEntry {
    /// Calls the user's `#[preflight]` function and returns the declared
    /// [`Preflight`][crate::preflight::Preflight].
    ///
    /// Always takes the active profile name as its single argument; the
    /// `#[preflight]` macro emits a thin adapter for the 0-arg form that
    /// discards the value.
    pub build_fn: fn(&str) -> crate::preflight::Preflight,
}

impl PreflightEntry {
    /// Constructs a [`PreflightEntry`]. Intended for use by the
    /// `#[preflight]` proc macro; not part of the stable public API.
    #[doc(hidden)]
    #[must_use]
    pub const fn new(build_fn: fn(&str) -> crate::preflight::Preflight) -> Self {
        Self { build_fn }
    }
}

unsafe impl Sync for PreflightEntry {}

/// All test cases discovered at compile time via `#[testcase]`.
///
/// Populated by [`linkme`] distributed slices; the coordinator iterates this
/// slice to build the list of tests to run.
#[linkme::distributed_slice]
pub static RIG_TEST_CASES: [TestCase];

/// At most one preflight entry, registered via `#[preflight]`.
///
/// The runtime asserts at startup that this slice contains zero or one
/// element.
#[linkme::distributed_slice]
pub static RIG_PREFLIGHT: [PreflightEntry];

/// At most one global setup entry, registered via `#[global_setup]`.
///
/// The runtime asserts at startup that this slice contains zero or one element.
#[linkme::distributed_slice]
pub static RIG_GLOBAL_SETUP: [GlobalSetupEntry];

/// At most one global teardown entry, registered via `#[global_teardown]`.
///
/// The runtime asserts at startup that this slice contains zero or one element.
#[linkme::distributed_slice]
pub static RIG_GLOBAL_TEARDOWN: [GlobalTeardownEntry];

/// An HTTP client configurator registered at compile time via
/// `#[rigtest::main(http_client = fn_name)]`.
///
/// At most one entry may exist per test binary. When present, the runtime calls
/// [`configure_fn`] with a fresh [`reqwest::ClientBuilder`] before each test
/// subprocess runs, and uses the returned builder to construct `ctx.client`.
///
/// Fields may be added in future releases. The `#[non_exhaustive]` attribute
/// prevents external code from constructing this struct via struct literal
/// syntax — use `#[rigtest::main(http_client = ...)]`.
///
/// [`configure_fn`]: HttpClientConfiguratorEntry::configure_fn
#[cfg(feature = "http-client")]
#[non_exhaustive]
pub struct HttpClientConfiguratorEntry {
    /// Calls the user's configure function, returning a modified builder or an error.
    ///
    /// On error the test subprocess exits with a descriptive message before
    /// running any test logic.
    pub configure_fn: fn(reqwest::ClientBuilder) -> Result<reqwest::ClientBuilder, BoxError>,
}

#[cfg(feature = "http-client")]
impl HttpClientConfiguratorEntry {
    /// Constructs an [`HttpClientConfiguratorEntry`]. Intended for use by the
    /// `#[rigtest::main]` proc macro; not part of the stable public API.
    #[doc(hidden)]
    #[must_use]
    pub const fn new(
        configure_fn: fn(reqwest::ClientBuilder) -> Result<reqwest::ClientBuilder, BoxError>,
    ) -> Self {
        Self { configure_fn }
    }
}

// linkme requires Sync
#[cfg(feature = "http-client")]
unsafe impl Sync for HttpClientConfiguratorEntry {}

/// At most one HTTP client configurator, registered via
/// `#[rigtest::main(http_client = fn_name)]`.
///
/// The runtime asserts at startup that this slice contains zero or one element.
#[cfg(feature = "http-client")]
#[linkme::distributed_slice]
pub static RIG_HTTP_CLIENT_CONFIGURATOR: [HttpClientConfiguratorEntry];

/// An SSH client configurator registered at compile time via
/// `#[rigtest::main(ssh_client = fn_name)]`.
///
/// At most one entry may exist per test binary. When present, the runtime calls
/// [`configure_fn`] with the destination string and a fresh [`openssh::SessionBuilder`]
/// before establishing each SSH connection, and uses the returned builder to connect.
///
/// # Platform support
///
/// This type is only available on Unix. The `ssh-client` feature depends on
/// [`openssh`], which requires the system `ssh` binary and is not supported on
/// non-Unix targets.
///
/// Fields may be added in future releases. The `#[non_exhaustive]` attribute
/// prevents external code from constructing this struct via struct literal
/// syntax — use `#[rigtest::main(ssh_client = ...)]`.
///
/// [`configure_fn`]: SshClientConfiguratorEntry::configure_fn
#[cfg(all(feature = "ssh-client", unix))]
#[non_exhaustive]
pub struct SshClientConfiguratorEntry {
    /// Calls the user's configure function with the destination and a fresh builder,
    /// returning a modified builder or an error.
    pub configure_fn:
        fn(&str, openssh::SessionBuilder) -> Result<openssh::SessionBuilder, BoxError>,
}

#[cfg(all(feature = "ssh-client", unix))]
impl SshClientConfiguratorEntry {
    /// Constructs an [`SshClientConfiguratorEntry`]. Intended for use by the
    /// `#[rigtest::main]` proc macro; not part of the stable public API.
    #[doc(hidden)]
    #[must_use]
    pub const fn new(
        configure_fn: fn(
            &str,
            openssh::SessionBuilder,
        ) -> Result<openssh::SessionBuilder, BoxError>,
    ) -> Self {
        Self { configure_fn }
    }
}

// linkme requires Sync
#[cfg(all(feature = "ssh-client", unix))]
unsafe impl Sync for SshClientConfiguratorEntry {}

/// At most one SSH client configurator, registered via
/// `#[rigtest::main(ssh_client = fn_name)]`.
///
/// The runtime asserts at startup that this slice contains zero or one element.
#[cfg(all(feature = "ssh-client", unix))]
#[linkme::distributed_slice]
pub static RIG_SSH_CLIENT_CONFIGURATOR: [SshClientConfiguratorEntry];
